### ISSUE TITLE
overloading /assets not possible

### ISSUE THREAD

**Issue by pazz** [lorenzschmid/jekyll-congress#14]
I hope you don't mind me dumping issues on you. Here's another one.

In order to overload some assets, such as the logo, I though I can simply create a folder `assets/images` and place only the logo file in there, and not creating a full copy of `assets` first
This is how I understood the jekyll docs at least. This does not seem to work because the presence of that folder makes jekyll forget about the corresponding one from the gem file.

```
bundle exec jekyll serve        
                                                           
Configuration file: /home/pazz/repo/orga/BCTCS2021/new/myblog/_config.yml
 Theme Config file: /home/pazz/repo/orga/BCTCS2021/new/jekyll-conference/_config.yml
            Source: /home/pazz/repo/orga/BCTCS2021/new/myblog
       Destination: /home/pazz/repo/orga/BCTCS2021/new/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    ------------------------------------------------
      Jekyll 4.0.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
	46: from /home/pazz/gems/bin/bundle:23:in `<main>'
	45: from /home/pazz/gems/bin/bundle:23:in `load'
	44: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	43: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	42: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	41: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	40: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	39: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	38: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	37: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	36: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	35: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	34: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	33: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	32: from /var/lib/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	31: from /home/pazz/gems/bin/jekyll:23:in `<top (required)>'
	30: from /home/pazz/gems/bin/jekyll:23:in `load'
	29: from /home/pazz/gems/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
	28: from /var/lib/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	27: from /var/lib/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	26: from /var/lib/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	25: from /var/lib/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	24: from /var/lib/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	23: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	22: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	21: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
	20: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	19: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:36:in `process'
	18: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:65:in `build'
	17: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/command.rb:28:in `process_site'
	16: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:78:in `process'
	15: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:218:in `write'
	14: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:342:in `each_site_file'
	13: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:342:in `each'
	12: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:343:in `block in each_site_file'
	11: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:343:in `each'
	10: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:344:in `block (2 levels) in each_site_file'
	 9: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/site.rb:219:in `block in write'
	 8: from /home/pazz/gems/gems/jekyll-4.0.1/lib/jekyll/static_file.rb:108:in `write'
	 7: from /usr/lib/ruby/2.7.0/fileutils.rb:581:in `rm'
	 6: from /usr/lib/ruby/2.7.0/fileutils.rb:581:in `each'
	 5: from /usr/lib/ruby/2.7.0/fileutils.rb:582:in `block in rm'
	 4: from /usr/lib/ruby/2.7.0/fileutils.rb:795:in `remove_file'
	 3: from /usr/lib/ruby/2.7.0/fileutils.rb:1464:in `remove_file'
	 2: from /usr/lib/ruby/2.7.0/fileutils.rb:1470:in `platform_support'
	 1: from /usr/lib/ruby/2.7.0/fileutils.rb:1465:in `block in remove_file'
/usr/lib/ruby/2.7.0/fileutils.rb:1465:in `unlink': Is a directory @ apply2files - /home/pazz/repo/orga/BCTCS2021/new/myblog/_site/assets (Errno::EISDIR)
```

**Comment by pazz** [comment]
Sorry, my bad. I accidentally copied old content into that a directory. I remember this issue from yesterday but wasn't able to reproduce properly.
